Mark Gasless DNSSEC as complete on roadmap
ensdomains/ensdomains-landing-v2 pull request #615
Opened 2024-03-21 12:34 UTC by gskril

2024-03-27 16:32 UTC, jefflau approved these changes

2024-03-28 00:58 UTC, TateB requested changes

2024-03-28 00:58 UTC, TateB commented on src/components/Roadmap/content/completed.json
> +        "tag": "Launched Jaunary 2023",
```suggestion
        "tag": "Launched Jaunary 2024",
```

2024-03-28 02:28 UTC, TateB approved these changes

2024-03-28 02:32 UTC, merged